### ISSUE TITLE
Link to evidence page is broken

### ISSUE THREAD

**Issue by averyngo34** [ibm-cloud-docs/devsecops#3]
Under the [section](https://cloud.ibm.com/docs/devsecops?topic=devsecops-cd-devsecops-pipelines#cd-devsecops-pipelines-inventory-workflow), the link to the [Evidence](https://cloud.ibm.com/docs/devsecops?topic=devsecops-cd-devsecops-evidence) page is broken.

**Comment by michaelbowler** [comment]
Link to the evidence page is now working - [Evidence](https://cloud.ibm.com/docs/devsecops?topic=devsecops-devsecops-evidence)

Pls close this issue.
