### ISSUE TITLE
Typo in Before you begin section

### ISSUE THREAD

**Issue by andrew-edgar** [ibm-cloud-docs/devsecops#7]
The text currently reads ...

"Stores the built artifacts metadate in inventory repository"

I believe that should be `metadata` not `metadate`

**Comment by andrew-edgar** [comment]
https://cloud.ibm.com/docs/devsecops?topic=devsecops-devsecops-tutorial-iac-ci

**Comment by michaelbowler** [comment]
Now resolved in https://cloud.ibm.com/docs/devsecops?topic=devsecops-devsecops-tutorial-iac-ci
